# Generated by Django 4.1.2 on 2022-12-18 10:27

import boards.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyUnits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelOfAnalyzer', models.CharField(max_length=250, null=True)),
                ('companyName1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.companyname')),
            ],
        ),
        migrations.CreateModel(
            name='CotNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(default=None, max_length=50, null=True)),
                ('PartNumber', models.CharField(default=None, max_length=50, null=True)),
                ('HosName', models.CharField(default=None, max_length=50, null=True)),
                ('CotNumber1', models.IntegerField(default=0, null=True)),
                ('InvoNumber1', models.IntegerField(default=0, null=True)),
                ('Datee', models.DateField(default=None, max_length=50, null=True)),
                ('ItemLot', models.CharField(default=None, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hospitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitalName', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceNumbero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(default=None, max_length=50, null=True)),
                ('PartNumber', models.CharField(default=None, max_length=50, null=True)),
                ('HosName', models.CharField(default=None, max_length=50, null=True)),
                ('CotNumber1', models.IntegerField(default=0, null=True)),
                ('InvoiceNumber1', models.IntegerField(default=0, null=True)),
                ('Datee', models.DateField(default=None, max_length=50, null=True)),
                ('ItemLot', models.CharField(default=None, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InvoiceNumber', models.IntegerField(default=0, null=True)),
                ('Status', models.CharField(default=None, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outInvoiceNumber', models.CharField(default=None, max_length=50, null=True)),
                ('Datao', models.DateField(default=None, max_length=50, null=True)),
                ('CompaniesNAme', models.CharField(default=None, max_length=50, null=True)),
                ('ItemName', models.CharField(default=None, max_length=50, null=True)),
                ('ItemPartNumber', models.CharField(default=None, max_length=50, null=True)),
                ('LtQTY', models.IntegerField(default=None, null=True)),
                ('Lots', models.CharField(default=None, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default=None, max_length=500, null=True)),
                ('mobile', models.CharField(default=None, max_length=500, null=True)),
                ('image', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InvoiceNumber', models.IntegerField(default=0, null=True)),
                ('Status', models.CharField(default=None, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=500, null=True)),
                ('cond', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShipperList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, null=True)),
                ('country', models.CharField(default=None, max_length=50, null=True)),
                ('profileMainAccount', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatedProfile', to='boards.profile')),
                ('profileshipper', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ownerProfile', to='boards.profile')),
            ],
        ),
        migrations.CreateModel(
            name='WorkFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfWorkFlow', models.CharField(max_length=250, null=True)),
                ('companyAnalyzers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.companyunits')),
                ('companyName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.companyname')),
            ],
        ),
        migrations.CreateModel(
            name='VendorList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, null=True)),
                ('country', models.CharField(default=None, max_length=50, null=True)),
                ('profileVendor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ownerProfileShipper', to='boards.profile')),
                ('shippervendor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ownerProfileVendor', to='boards.shipperlist')),
            ],
        ),
        migrations.CreateModel(
            name='TeamLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, null=True)),
                ('role', models.CharField(default=None, max_length=50, null=True)),
                ('ProfileMainUser', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatedMainProfile', to='boards.profile')),
                ('profileTeamLeader', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TeamLeaderProfile', to='boards.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, null=True)),
                ('nationality', models.CharField(default=None, max_length=50, null=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='boards.profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='boards.role'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Loto', models.CharField(default=None, max_length=50, null=True)),
                ('LotQTY', models.IntegerField(default=None, null=True)),
                ('AllLotQTY', models.IntegerField(default=None, null=True)),
                ('JNum', models.CharField(default=None, max_length=50, null=True)),
                ('Lot_outInvoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.outinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='ItemInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfItem', models.CharField(max_length=255, null=True)),
                ('mainUser', models.CharField(max_length=255, null=True)),
                ('teamLeader', models.CharField(max_length=255, null=True)),
                ('engineerName', models.CharField(max_length=255, null=True)),
                ('dateOfArrival', models.DateField(max_length=50, null=True)),
                ('partNumber', models.CharField(default=None, max_length=255, null=True)),
                ('cost', models.IntegerField(default=0, null=True)),
                ('Item_Model_compName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.companyname')),
                ('Item_Model_compUnit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.companyunits')),
                ('Item_Model_workFlow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.workflow')),
                ('Item_outInvoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.outinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='Imag3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(null=True, upload_to=boards.models.path_and_renameListing3)),
                ('Inpu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.iteminput')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalsAnalyzers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SerialNumber', models.CharField(max_length=250, null=True)),
                ('HosNam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.hospitals')),
                ('WorFlo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.workflow')),
                ('compNam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.companyname')),
                ('compUni', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.companyunits')),
            ],
        ),
        migrations.CreateModel(
            name='FollowerList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, null=True)),
                ('country', models.CharField(default=None, max_length=50, null=True)),
                ('profileFollower', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ownerProfileVendors', to='boards.profile')),
                ('vendorFollower', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ownerProfileFollowr', to='boards.vendorlist')),
            ],
        ),
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, null=True)),
                ('role', models.CharField(default=None, max_length=50, null=True)),
                ('TLeaderEngineer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ownerProfileEngineer', to='boards.teamleader')),
                ('profileEngineer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ownerProfileTeamLeader', to='boards.profile')),
            ],
        ),
        migrations.CreateModel(
            name='BookStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QTYOfItem', models.IntegerField(default=0, null=True)),
                ('StatusOfItem', models.CharField(default=None, max_length=50, null=True)),
                ('RemainingQTY', models.IntegerField(default=0, null=True)),
                ('BookedLot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.lot')),
                ('NameOfItem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.iteminput')),
                ('nameOfUser', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssembledStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemId', models.CharField(default=None, max_length=255, null=True)),
                ('ItemName', models.CharField(default=None, max_length=255, null=True)),
                ('Dato', models.DateField(default=None, max_length=50, null=True)),
                ('partNumber', models.CharField(default=None, max_length=255, null=True)),
                ('QTY', models.CharField(default=None, max_length=255, null=True)),
                ('Price', models.CharField(default=None, max_length=255, null=True)),
                ('InvoNum', models.CharField(default=None, max_length=255, null=True)),
                ('Cot', models.CharField(default=None, max_length=255, null=True)),
                ('HosName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.hospitals')),
                ('Invo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.invoicestatus')),
                ('Item_Model_compName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.companyname')),
                ('Item_Model_compUnit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.companyunits')),
                ('Item_Model_workFlow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.workflow')),
                ('LotNum', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.lot')),
                ('nameOfUser', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
