# Generated by Django 4.1.2 on 2023-01-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assembledstore',
            name='Price',
            field=models.IntegerField(default=None, max_length=255, null=True),
        ),
    ]
