# Generated by Django 4.1.2 on 2023-01-23 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_alter_assembledstore_price_alter_iteminput_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminput',
            name='Pric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.price'),
        ),
        migrations.AlterField(
            model_name='iteminput',
            name='cost',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
