# Generated by Django 4.1.2 on 2023-01-23 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_iteminput_pric_alter_iteminput_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iteminput',
            name='Pric',
        ),
    ]
