# Generated by Django 4.1.2 on 2023-02-09 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_remove_iteminput_pric'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(default=None, max_length=255, null=True)),
                ('partNumber', models.CharField(default=None, max_length=255, null=True)),
                ('Price', models.IntegerField(default=None, null=True)),
                ('QuotStatus', models.CharField(default=None, max_length=255, null=True)),
                ('Item_Model_compName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.companyname')),
                ('Item_Model_compUnit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.companyunits')),
                ('Item_Model_workFlow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.workflow')),
            ],
        ),
    ]
