# Generated by Django 4.1.2 on 2023-02-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_undertest_delete_quotationinput'),
    ]

    operations = [
        migrations.AddField(
            model_name='undertest',
            name='Note',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
