# Generated by Django 4.1.2 on 2023-02-27 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_undertest_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='undertest',
            name='LotNum',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.lot'),
        ),
    ]
