# Generated by Django 4.1.2 on 2023-03-10 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0011_alter_undertest_lotnum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='undertest',
            name='LotNum',
        ),
    ]
