# Generated by Django 4.1.2 on 2023-03-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0014_undertest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizeName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizeName', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
    ]
