# Generated by Django 4.1.2 on 2023-03-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0015_organizename'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ParameterNam', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
    ]
