# Generated by Django 4.1.2 on 2023-03-30 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0016_parametername'),
    ]

    operations = [
        migrations.CreateModel(
            name='OraderCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QTY', models.CharField(default=None, max_length=255, null=True)),
                ('dat', models.CharField(default=None, max_length=255, null=True)),
                ('Note', models.CharField(default=None, max_length=255, null=True)),
                ('ElementName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.parametername')),
                ('Item_Model_compName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.companyname')),
                ('Item_Model_compUnit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.companyunits')),
                ('OrganizeNam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.organizename')),
            ],
        ),
    ]
