# Generated by Django 4.1.2 on 2023-03-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0017_oradercreation'),
    ]

    operations = [
        migrations.AddField(
            model_name='oradercreation',
            name='status',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
