# Generated by Django 4.1.2 on 2023-03-31 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0019_parametername_item_model_compname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oradercreation',
            name='orderNum',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
