# Generated by Django 4.1.2 on 2023-04-02 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0020_oradercreation_ordernum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oradercreation',
            name='ElementName',
        ),
        migrations.RemoveField(
            model_name='oradercreation',
            name='QTY',
        ),
        migrations.CreateModel(
            name='ElementCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QTY', models.CharField(default=None, max_length=255, null=True)),
                ('dat', models.CharField(default=None, max_length=255, null=True)),
                ('Note', models.CharField(default=None, max_length=255, null=True)),
                ('status', models.CharField(default=None, max_length=255, null=True)),
                ('orderNum', models.CharField(default=None, max_length=255, null=True)),
                ('ElementName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.parametername')),
            ],
        ),
    ]
