# Generated by Django 4.1.2 on 2023-04-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0023_elementconfermation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementcreation',
            name='QTY',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
