# Generated by Django 4.1.2 on 2023-04-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0024_alter_elementcreation_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametername',
            name='CatNumber',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
