# Generated by Django 4.1.2 on 2023-04-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0025_parametername_catnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametername',
            name='slideNumber',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
