# Generated by Django 4.1.2 on 2023-04-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0026_parametername_slidenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametername',
            name='slideNumber',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
