# Generated by Django 4.1.2 on 2023-04-10 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0028_remove_parametername_catnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementcreation',
            name='CatNumber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.reagentqty'),
        ),
    ]
