# Generated by Django 4.1.2 on 2023-04-10 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0030_elementcreation_slidesqty'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementconfermation',
            name='CatNumber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.reagentqty'),
        ),
        migrations.AddField(
            model_name='elementconfermation',
            name='ExpiryDate',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='elementconfermation',
            name='SlidesQTY',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
