# Generated by Django 4.1.2 on 2023-04-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0033_alter_oradercreation_dat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oradercreation',
            name='dat',
            field=models.DateTimeField(default=None, max_length=255, null=True),
        ),
    ]
