# Generated by Django 4.1.2 on 2023-04-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0035_alter_oradercreation_dat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oradercreation',
            name='dat',
            field=models.DateField(default=None, max_length=50, null=True),
        ),
    ]
