# Generated by Django 4.1.2 on 2023-04-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0038_orderinvoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinvoice',
            name='ElementName',
        ),
        migrations.AddField(
            model_name='orderinvoice',
            name='InvoiceNumber',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
