# Generated by Django 4.1.2 on 2023-04-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0039_remove_orderinvoice_elementname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementconfermation',
            name='ExpiryDate',
            field=models.DateField(default=None, max_length=255, null=True),
        ),
    ]
