# Generated by Django 4.1.2 on 2023-04-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0040_alter_elementconfermation_expirydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='reagentqty',
            name='Price',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
