# Generated by Django 4.1.2 on 2023-04-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0041_reagentqty_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reagentqty',
            name='Price',
            field=models.FloatField(default=None, null=True),
        ),
    ]
