# Generated by Django 4.1.2 on 2023-04-18 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0042_alter_reagentqty_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinvoice',
            name='orderConfermation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.elementconfermation'),
        ),
    ]
