# Generated by Django 4.1.2 on 2023-04-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0043_orderinvoice_orderconfermation'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementconfermation',
            name='ConfNum',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
