# Generated by Django 4.1.2 on 2023-04-19 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0044_elementconfermation_confnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinvoice',
            name='orderConfermation',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
