# Generated by Django 4.1.2 on 2023-04-22 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0046_reagentqty_cal_shipping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calibrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cal', models.CharField(default=None, max_length=255, null=True)),
                ('Item_Model_compName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.companyname')),
                ('Item_Model_compUnit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.companyunits')),
                ('ParName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.parametername')),
            ],
        ),
    ]
