# Generated by Django 4.1.2 on 2023-05-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0050_excelfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelfile',
            name='file',
            field=models.FileField(upload_to='images/'),
        ),
    ]
