# Generated by Django 4.1.2 on 2023-05-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0051_alter_excelfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelfile',
            name='file',
            field=models.FileField(upload_to='path_and_renameListing'),
        ),
    ]
