# Generated by Django 4.1.2 on 2023-05-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0055_alter_excelfile_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autoconfdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderNumber', models.CharField(default=None, max_length=255, null=True)),
                ('PO', models.CharField(default=None, max_length=255, null=True)),
                ('MatDesc', models.CharField(default=None, max_length=255, null=True)),
                ('BatchNum', models.CharField(default=None, max_length=255, null=True)),
                ('ExpiryDate', models.CharField(default=None, max_length=255, null=True)),
                ('OrderQTY', models.CharField(default=None, max_length=255, null=True)),
                ('CumConfQTY', models.CharField(default=None, max_length=255, null=True)),
                ('UnitPrice', models.CharField(default=None, max_length=255, null=True)),
                ('NetVal', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
    ]
