# Generated by Django 4.1.2 on 2023-05-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0057_autoconfdata_matrial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementconfermation',
            name='SlidesQTY',
            field=models.FloatField(default=None, null=True),
        ),
    ]
