# Generated by Django 4.1.2 on 2023-05-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0062_alter_autoconfdata_expirydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementconfermation',
            name='BatchNumber',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
