# Generated by Django 4.1.2 on 2023-05-11 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0066_autoorderinvoice_catnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoorderinvoice',
            name='ElementName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.parametername'),
        ),
        migrations.AddField(
            model_name='autoorderinvoice',
            name='QTY',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='autoorderinvoice',
            name='SlidesQTY',
            field=models.FloatField(default=None, null=True),
        ),
    ]
