# Generated by Django 4.1.2 on 2023-05-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0067_autoorderinvoice_elementname_autoorderinvoice_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoorderinvoice',
            name='Price',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='orderinvoice',
            name='Price',
            field=models.FloatField(default=None, null=True),
        ),
    ]
