# Generated by Django 4.1.2 on 2023-05-15 21:47

import boards.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0070_remove_shipping_cal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFileOrderCrea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=boards.models.path_and_renameListing2)),
            ],
        ),
        migrations.CreateModel(
            name='AutoElementCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SlidesQTY', models.IntegerField(default=None, null=True)),
                ('QTY', models.IntegerField(default=None, null=True)),
                ('dat', models.CharField(default=None, max_length=255, null=True)),
                ('status', models.CharField(default=None, max_length=255, null=True)),
                ('orderNum', models.CharField(default=None, max_length=255, null=True)),
                ('CatNumber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.reagentqty')),
                ('ElementName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.parametername')),
                ('Item_Model_compName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.companyname')),
                ('Item_Model_compUnit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.companyunits')),
            ],
        ),
    ]
