# Generated by Django 4.1.2 on 2023-05-16 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0071_excelfileordercrea_autoelementcreation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementcreation',
            name='Note',
        ),
    ]
