# Generated by Django 4.1.2 on 2023-05-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0072_remove_elementcreation_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementcreation',
            name='Note',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
