# Generated by Django 4.1.2 on 2023-05-19 14:56

import boards.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0073_elementcreation_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFileInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=boards.models.path_and_renameListing3)),
                ('ordinv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.orderinvoice')),
            ],
        ),
    ]
