# Generated by Django 4.1.2 on 2023-05-21 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0078_excelfileinvoice_ordnum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelfile',
            name='ordnum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.oradercreation'),
        ),
    ]
