# Generated by Django 4.1.2 on 2023-05-21 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0079_excelfile_ordnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelfileordercrea',
            name='ordnum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.oradercreation'),
        ),
    ]
