# Generated by Django 4.1.2 on 2023-07-05 10:13

import boards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0080_excelfileordercrea_ordnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imag3',
            name='images',
            field=models.FileField(null=True, upload_to=boards.models.path_and_renameListing4),
        ),
    ]
