# Generated by Django 4.1.2 on 2023-07-05 11:17

import boards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0081_alter_imag3_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imag3',
            name='images',
            field=models.ImageField(null=True, upload_to=boards.models.path_and_renameListing4),
        ),
    ]
