# Generated by Django 4.1.2 on 2023-07-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0082_alter_imag3_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='reagentqty',
            name='GTIN',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
