# Generated by Django 4.1.2 on 2023-07-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0083_reagentqty_gtin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reagentqty',
            name='GTIN',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
