# Generated by Django 4.1.2 on 2023-10-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0084_alter_reagentqty_gtin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(null=True, upload_to='images/Signup/'),
        ),
    ]
