# Generated by Django 4.1.2 on 2023-10-22 19:53

import boards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0085_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(null=True, upload_to=boards.models.path_and_renameListing5),
        ),
    ]
