# Generated by Django 4.1.2 on 2023-10-27 14:47

import boards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0088_jobsheet_alter_profile_image_jobsheetimg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsheet',
            name='nameOfItem',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(null=True, upload_to=boards.models.path_and_renameListing5),
        ),
    ]
