# Generated by Django 4.1.2 on 2023-10-30 13:17

import boards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0090_hospitalsanalyzers_counter_hospitalsanalyzers_pm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(null=True, upload_to=boards.models.path_and_renameListing1),
        ),
    ]
