# Generated by Django 4.1.2 on 2023-11-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0093_alter_hospitalsanalyzers_pm'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicenumbero',
            name='Price',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
