# Generated by Django 4.1.2 on 2023-11-13 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0094_invoicenumbero_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkFlowLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HosName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.hospitals')),
                ('UserName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
