# Generated by Django 4.1.2 on 2023-12-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0096_workflowline_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalsanalyzers',
            name='Earth',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
