# Generated by Django 4.1.2 on 2023-12-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0097_hospitalsanalyzers_earth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GovernorateName', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
