# Generated by Django 4.1.2 on 2023-12-01 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0098_governorate'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalsanalyzers',
            name='Govern',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.governorate'),
        ),
    ]
