# Generated by Django 4.1.2 on 2023-12-08 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0099_hospitalsanalyzers_govern'),
    ]

    operations = [
        migrations.CreateModel(
            name='TDS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TDS', models.CharField(max_length=250, null=True)),
                ('Datao', models.DateField(default=None, max_length=50, null=True)),
                ('HosNam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.hospitalsanalyzers')),
            ],
        ),
    ]
